"""
Filename: quiz.py
Author: Efrain Gomez Fajardo
Purpose: Definition of the Question class and the derived classes
"""

class Question:
    """
    This class represents a quiz that the user will have, generated by an AI.
    """
    __question: dict
    __is_correct: bool

    def __init__(self, question:dict):
        """
        Create a new question.
        """
        self.__question = question
        self.__is_correct = False

    def _generate_response(self, answer:str) -> None:
        """
        Give an answer back to the user depending on what they answered
        """
        if answer.lower() == self.__question["answer"]:
            self.__is_correct = True
            print("Correct!")
        else:
            print("That is not correct.")

    def answer(self) -> None:
        """
        Allow the user to answer to the question
        """
        if not self.__is_correct:
            print(self.__question["question"])
            print(self.__question["options"])
            answer = input("> ")
            self._generate_response(answer)

    def get_result(self) -> bool:
        """
        Returns if the answer was answered
        correctly or incorrectly.
        'True' if it was correct.
        """
        return self.__is_correct
    
    def reset(self) -> None:
        """
        Go back to the original state
        """
        self.__is_correct = False

    # ---------------------------
    # OVERRIDING METHODS
    # ---------------------------
    def __str__(self) -> str:
        """
        Overriding so we can easily print the quiz to the user
        """
        return self.__question["question"]


class MultipleChoice(Question):
    """
    A multiple choice question
    """
    # Same attributes as the parent.
    
    def __init__(self, question:str):
        """
        Create a new multiple choice
        """
        super().__init__(question)
